import { INodeProperties } from 'n8n-workflow';

export { findProduct } from './findProduct.operation';
export { purchaseProduct } from './purchaseProduct.operation';

export const checkoutFields: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['checkout'] } },
		options: [
			{
				name: 'Create Order',
				value: 'findProduct',
				description: 'Search and find products on Amazon and Shopify',
				action: 'Create order',
			},
			{
				name: 'Pay Order',
				value: 'purchaseProduct',
				description: 'Purchase a product with automated checkout',
				action: 'Pay order',
			},
		],
		default: 'findProduct',
	},
	{
		displayName: 'Platform',
		name: 'platform',
		type: 'options',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		options: [
			{ name: 'Amazon', value: 'amazon', description: 'Amazon marketplace' },
			{ name: 'Shopify', value: 'shopify', description: 'Shopify store' },
		],
		default: 'amazon',
		description: 'E-commerce platform for the purchase',
		required: true,
	},
	// ---- Find Product fields (all fields needed for POST /orders)

	// ---- Purchase Product fields (Step 2: Submit Transaction)
	{
		displayName: 'Serialized Transaction',
		name: 'serializedTransaction',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['purchaseProduct'] } },
		default: '',
		placeholder: 'Copy from Find Product response: order.payment.preparation.serializedTransaction',
		description: 'Serialized transaction from Find Product response',
		required: true,
	},
	{
		displayName: 'Payment Chain',
		name: 'paymentMethod',
		type: 'options',
		displayOptions: { show: { resource: ['checkout'], operation: ['purchaseProduct'] } },
		options: [
			{ name: 'Arbitrum', value: 'arbitrum', description: 'Arbitrum network' },
			{ name: 'Arbitrum Sepolia', value: 'arbitrum-sepolia', description: 'Arbitrum testnet' },
			{ name: 'Base', value: 'base', description: 'Base network' },
			{ name: 'Base Sepolia', value: 'base-sepolia', description: 'Base testnet' },
			{ name: 'Ethereum', value: 'ethereum', description: 'Ethereum mainnet' },
			{ name: 'Ethereum Sepolia', value: 'ethereum-sepolia', description: 'Ethereum testnet' },
			{ name: 'Optimism', value: 'optimism', description: 'Optimism network' },
			{ name: 'Optimism Sepolia', value: 'optimism-sepolia', description: 'Optimism testnet' },
			{ name: 'Polygon', value: 'polygon', description: 'Polygon network' },
			{ name: 'Polygon Amoy', value: 'polygon-amoy', description: 'Polygon testnet' },
			{ name: 'World Chain Sepolia', value: 'world-chain-sepolia', description: 'World Chain testnet' },
		],
		default: 'arbitrum-sepolia',
		description: 'Payment method for completing the transaction',
		required: true,
	},
	{
		displayName: 'Payer Wallet Address',
		name: 'payerAddress',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['purchaseProduct'] } },
		default: '',
		placeholder: '0x1234567890123456789012345678901234567890',
		description: 'Agent wallet address for crypto payments - must be a Crossmint managed wallet with USDC funds',
		required: true,
	},
	// External signer is always required for Pay Order
	{
		displayName: 'Private Key',
		name: 'purchasePrivateKey',
		type: 'string',
		typeOptions: { password: true },
		displayOptions: { show: { resource: ['checkout'], operation: ['purchaseProduct'] } },
		default: '',
		placeholder: '0x1234... for EVM or base58 for Solana',
		description: 'Private key to sign with (32-byte hex for EVM, base58 for Solana) - External signer is required',
		required: true,
	},
	{
		displayName: 'Product Identifier',
		name: 'productIdentifier',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'], platform: ['amazon'] } },
		default: '',
		placeholder: 'B01DFKC2SO or https://www.amazon.com/dp/B01DFKC2SO',
		description: 'Amazon ASIN (e.g. B01DFKC2SO) or full Amazon product URL',
		required: true,
	},
	{
		displayName: 'Product Identifier',
		name: 'productIdentifier',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'], platform: ['shopify'] } },
		default: '',
		placeholder: 'https://store.shopify.com/products/product-handle',
		description: 'Full Shopify product URL (will use default variant)',
		required: true,
	},
	{
		displayName: 'Recipient Email',
		name: 'recipientEmail',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		default: '',
		placeholder: 'recipient@example.com',
		description: 'Email address of the person receiving the product',
		required: true,
	},
	{
		displayName: 'Recipient Name',
		name: 'recipientName',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		default: '',
		placeholder: 'Manuel Paella',
		description: 'Full name of the recipient',
		required: true,
	},
	{
		displayName: 'Address Line 1',
		name: 'addressLine1',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		default: '',
		placeholder: '123 Fake Street',
		description: 'Street address, P.O. box, company name, c/o.',
		required: true,
	},
	{
		displayName: 'Address Line 2 (Optional)',
		name: 'addressLine2',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		default: '',
		placeholder: 'Apartment 4B',
		description: 'Apartment, suite, unit, building, floor, etc',
	},
	{
		displayName: 'City',
		name: 'city',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		default: '',
		placeholder: 'Valencia',
		description: 'City, district, suburb, town, or village',
		required: true,
	},
	{
		displayName: 'State',
		name: 'state',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		default: '',
		placeholder: 'FL',
		description: 'US State (required)',
		required: true,
	},
	{
		displayName: 'ZIP Code',
		name: 'postalCode',
		type: 'string',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		default: '',
		placeholder: '33130',
		description: 'US ZIP code',
		required: true,
	},
	{
		displayName: 'Country',
		name: 'country',
		type: 'options',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		options: [
			{ name: 'United States', value: 'US' },
		],
		default: 'US',
		description: 'Two-letter country code (ISO 3166-1 alpha-2)',
		required: true,
	},
	{
		displayName: 'Environment',
		name: 'environment',
		type: 'options',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'] } },
		options: [
			{ name: 'Staging (Testnet)', value: 'staging', description: 'Use testnet chains for testing' },
			{ name: 'Production (Mainnet)', value: 'production', description: 'Use mainnet chains for real transactions' },
		],
		default: 'staging',
		description: 'Environment to use for payment methods',
		required: true,
	},
	{
		displayName: 'Payment Chain',
		name: 'paymentMethod',
		type: 'options',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'], environment: ['staging'] } },
		options: [
			{ name: 'Arbitrum Sepolia', value: 'arbitrum-sepolia', description: 'Arbitrum testnet' },
			{ name: 'Base Sepolia', value: 'base-sepolia', description: 'Base testnet' },
			{ name: 'Ethereum Sepolia', value: 'ethereum-sepolia', description: 'Ethereum testnet' },
			{ name: 'Optimism Sepolia', value: 'optimism-sepolia', description: 'Optimism testnet' },
			{ name: 'Polygon Amoy', value: 'polygon-amoy', description: 'Polygon testnet' },
			{ name: 'World Chain Sepolia', value: 'world-chain-sepolia', description: 'World Chain testnet' },
		],
		default: 'arbitrum-sepolia',
		description: 'Payment method for the purchase (Staging/Testnet)',
		required: true,
	},
	{
		displayName: 'Payment Chain',
		name: 'paymentMethod',
		type: 'options',
		displayOptions: { show: { resource: ['checkout'], operation: ['findProduct'], environment: ['production'] } },
		options: [
			{ name: 'Arbitrum', value: 'arbitrum', description: 'Arbitrum network' },
			{ name: 'Base', value: 'base', description: 'Base network' },
			{ name: 'Ethereum', value: 'ethereum', description: 'Ethereum mainnet' },
			{ name: 'Optimism', value: 'optimism', description: 'Optimism network' },
			{ name: 'Polygon', value: 'polygon', description: 'Polygon network' },
		],
		default: 'ethereum',
		description: 'Payment method for the purchase (Production/Mainnet)',
		required: true,
	},
	{
		displayName: 'Payment Currency',
		name: 'paymentCurrency',
		type: 'options',
		displayOptions: {
			show: {
				resource: ['checkout'],
				operation: ['findProduct'],
				paymentMethod: ['ethereum-sepolia', 'polygon-amoy', 'base-sepolia', 'arbitrum-sepolia', 'optimism-sepolia', 'world-chain-sepolia', 'ethereum', 'polygon', 'base', 'arbitrum', 'optimism'],
			},
		},
		options: [
			{ name: 'USDC', value: 'usdc', description: 'USD Coin (Only supported currency)' },
		],
		default: 'usdc',
		description: 'Cryptocurrency to pay with (USDC only)',
		required: true,
	},
	{
		displayName: 'Payer Wallet Address',
		name: 'payerAddress',
		type: 'string',
		displayOptions: {
			show: {
				resource: ['checkout'],
				operation: ['findProduct'],
				paymentMethod: ['ethereum-sepolia', 'polygon-amoy', 'base-sepolia', 'arbitrum-sepolia', 'optimism-sepolia', 'world-chain-sepolia', 'ethereum', 'polygon', 'base', 'arbitrum', 'optimism'],
			},
		},
		default: '',
		placeholder: '0x1234567890123456789012345678901234567890',
		description: 'Agent wallet address for crypto payments - must be a Crossmint managed wallet with USDC funds',
		required: true,
	},
];
